import { FilesystemItem } from "./types";

export const filesystem: FilesystemItem[] = [
  { type: "directory", path: "/1099" },
  { type: "directory", path: "/1099/2025" },
  {
    type: "file",
    path: "/1099/2025/comunal.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2025/diana kova.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2025/molly and her week of wonders.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2025/artifaxing + wins.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2025/eunuch for the kingdom.md",
    contentType: "text",
    src: "/test.txt",
  },
  { type: "directory", path: "/1099/2024" },
  {
    type: "file",
    path: "/1099/2024/masonic musik.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2024/chalkhead's playground.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2024/awaken.md",
    contentType: "text",
    src: "/test.txt",
  },
  {
    type: "file",
    path: "/1099/2024/seekr trending.md",
    contentType: "text",
    src: "/test.txt",
  },
  { type: "directory", path: "/w-2" },
  { type: "directory", path: "/w-2/2021 - now" },
  {
    type: "file",
    path: "/w-2/2021 - now/offsec.md",
    contentType: "text",
    src: "/test.txt",
  },
  { type: "directory", path: "/w-2/2020 - 2021" },
  {
    type: "file",
    path: "/w-2/2020 - 2021/begeeked labs.md",
    contentType: "text",
    src: "/test.txt",
  },
  { type: "directory", path: "/fun" },
  { type: "directory", path: "/fun/2025" },
  { type: "directory", path: "/fun/2024" },
  { type: "directory", path: "/fun/2023" },
  { type: "directory", path: "/fun/2022" },
  { type: "directory", path: "/fun/2021" },
  { type: "directory", path: "/fun/2019" },
  { type: "directory", path: "/fun/2016" },
  { type: "file", path: "/find me.md", contentType: "text", src: "/test.txt" },
];
