import { FilesystemItem } from "./types";

export const filesystem: FilesystemItem[] = [
  { type: "directory", path: "/1099" },
  { type: "directory", path: "/1099/2025" },
  { type: "file", path: "/1099/2025/comunal.md", content: "" },
  { type: "file", path: "/1099/2025/diana kova.md", content: "" },
  {
    type: "file",
    path: "/1099/2025/molly and her week of wonders.md",
    content: "",
  },
  { type: "file", path: "/1099/2025/artifaxing + wins.md", content: "" },
  { type: "file", path: "/1099/2025/eunuch for the kingdom.md", content: "" },
  { type: "directory", path: "/1099/2024" },
  { type: "file", path: "/1099/2024/masonic musik.md", content: "" },
  { type: "file", path: "/1099/2024/chalkhead's playground.md", content: "" },
  { type: "file", path: "/1099/2024/awaken.md", content: "" },
  { type: "file", path: "/1099/2024/seekr trending.md", content: "" },
  { type: "directory", path: "/w-2" },
  { type: "directory", path: "/w-2/2021 - now" },
  { type: "file", path: "/w-2/2021 - now/offsec.md", content: "" },
  { type: "directory", path: "/w-2/2020 - 2021" },
  { type: "file", path: "/w-2/2020 - 2021/begeeked labs.md", content: "" },
  { type: "directory", path: "/fun" },
  { type: "directory", path: "/fun/2025" },
  { type: "directory", path: "/fun/2024" },
  { type: "directory", path: "/fun/2023" },
  { type: "directory", path: "/fun/2022" },
  { type: "directory", path: "/fun/2021" },
  { type: "directory", path: "/fun/2019" },
  { type: "directory", path: "/fun/2016" },
  { type: "file", path: "/find me.md", content: "" },
];
